name: Build and Release Binaries

on:
  push:
    tags:
      - "v*"

permissions:
  # This permission is required for the gh CLI to create releases and upload assets.
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: arm64
          - goos: darwin
            goarch: amd64
          - goos: darwin
            goarch: arm64
          - goos: windows
            goarch: amd64

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24" # Or match the version in your go.mod

      - name: Build binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          BINARY_NAME="tailwind-sorter"
          if [ "$GOOS" == "windows" ]; then
            BINARY_NAME+=".exe"
          fi
          VERSION="${{ github.ref_name }}"
          # Use -trimpath to create reproducible builds and -s -w to shrink the binary size.
          go build -trimpath -ldflags="-s -w -X 'github.com/dexter2389/go-tailwind-sorter/cmd.Version=${VERSION}'" -o "dist/${BINARY_NAME}" .

      - name: Create archive
        id: archive # Give the step an ID to reference its outputs
        run: |
          # The base name for the archive, without extension.
          ARCHIVE_BASENAME="tailwind-sorter-${{ github.ref_name }}-${{ matrix.goos }}-${{ matrix.goarch }}"

          # Copy essential files into the distribution folder.
          cp LICENSE README.md dist/

          # Create the platform-specific archive and set the output variable.
          if [ "${{ matrix.goos }}" == "windows" ]; then
            ARCHIVE_PATH="${ARCHIVE_BASENAME}.zip"
            cd dist && zip -r "../${ARCHIVE_PATH}" . && cd ..
          else
            ARCHIVE_PATH="${ARCHIVE_BASENAME}.tar.gz"
            tar -czf "${ARCHIVE_PATH}" -C dist .
          fi

          # Use a GitHub step output to pass the archive path to the next step.
          echo "path=${ARCHIVE_PATH}" >> $GITHUB_OUTPUT

      # This step now uses the output from the 'archive' step.
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          # Use a consistent name for the artifact container.
          name: tailwind-sorter-${{ matrix.goos }}-${{ matrix.goarch }}
          # The path is now dynamically set from the previous step's output.
          path: ${{ steps.archive.outputs.path }}
          if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      # This is the new step using the official GitHub CLI.
      - name: Create GitHub Release
        env:
          # The GITHUB_TOKEN is required for the gh CLI to authenticate.
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Use gh release create to create a new release.
          # The command takes the tag name as the first argument.
          # The final arguments are the files to upload as assets.
          gh release create ${{ github.ref_name }} \
            --title "Release ${{ github.ref_name }}" \
            artifacts/*/*
